# POSTWORK 5
* Explora tu dataset con el fin de encontrar los NaNs que contiene. Piensa en la distribución de NaNs por columna y por fila.
* Piensa cuáles son los procedimientos que puedes aplicar a tus NaNs. ¿Tenemos que eliminar las filas/columnas que tienen esos NaNs? ¿O podríamos rellenar esos NaNs con algún valor de manera que podamos retener esas filas/columnas?
* Limpia tu dataset de manera que no quede ningún NaN.
* Reindexa tu dataset si lo consideras necesario.
* Renombra tus columnas si lo consideras necesario.
* Prueba aplicar agregaciones a tu DataFrame para ver si puedes empezar a responder algunas de las preguntas que te planteaste anteriormente. Aquí tienes una lista de algunas de las funciones que puedes utilizar para agregar/reducir tu dataset: IMG Si tienes cualquier duda, ¡pregúntale a tu experto!

In [1]:
import pandas as pd #importamos pandas
import numpy as np #importando numpy

In [2]:
datos =  pd.read_csv("https://raw.githubusercontent.com/McGilfordJose/BEDU/main/Python/Datasets/Consolidado.csv", encoding='ISO-8859-1')
datos

      Año  ... COVID.19
0    2005  ...        0
1    2005  ...        0
2    2005  ...        0
3    2005  ...        0
4    2005  ...        0
..    ...  ...      ...
187  2020  ...        1
188  2020  ...        1
189  2020  ...        1
190  2020  ...        1
191  2020  ...        1

[192 rows x 59 columns]

In [3]:
datos.head()

    Año  ... COVID.19
0  2005  ...        0
1  2005  ...        0
2  2005  ...        0
3  2005  ...        0
4  2005  ...        0

[5 rows x 59 columns]

In [4]:
datos.tail()

      Año  ... COVID.19
187  2020  ...        1
188  2020  ...        1
189  2020  ...        1
190  2020  ...        1
191  2020  ...        1

[5 rows x 59 columns]

In [5]:
indexes = datos["Año"]
indexes

0      2005
1      2005
2      2005
3      2005
4      2005
       ...
187    2020
188    2020
189    2020
190    2020
191    2020
Name: Año, Length: 192, dtype: int64

In [36]:
lista = range(1,len(datos)+1)
lista[191]
datos.index=lista

In [37]:
datos.isna().sum(axis=1)

1      1
2      1
3      1
4      1
5      1
      ..
188    0
189    0
190    0
191    0
192    0
Length: 192, dtype: int64

In [38]:
datos=datos.fillna(0)
datos

      Año  ... COVID.19
1    2005  ...        0
2    2005  ...        0
3    2005  ...        0
4    2005  ...        0
5    2005  ...        0
..    ...  ...      ...
188  2020  ...        1
189  2020  ...        1
190  2020  ...        1
191  2020  ...        1
192  2020  ...        1

[192 rows x 59 columns]

In [39]:
datos.isna().sum(axis=1) #Checamos que no tengamos NAN

1      0
2      0
3      0
4      0
5      0
      ..
188    0
189    0
190    0
191    0
192    0
Length: 192, dtype: int64

In [40]:
datos.head()

    Año  ... COVID.19
1  2005  ...        0
2  2005  ...        0
3  2005  ...        0
4  2005  ...        0
5  2005  ...        0

[5 rows x 59 columns]

In [41]:
datos.describe()

              Año  ...    COVID.19
count   192.00000  ...  192.000000
mean   2012.84375  ...    0.046875
std       4.63388  ...    0.211924
min    2005.00000  ...    0.000000
25%    2008.75000  ...    0.000000
50%    2013.00000  ...    0.000000
75%    2017.00000  ...    0.000000
max    2020.00000  ...    1.000000

[8 rows x 58 columns]

In [42]:
datos.dtypes

Año                                                                                                int64
Mes                                                                                               object
Población total                                                                                    int64
Población de 15 años y más                                                                         int64
Población económicamente activa (PEA)                                                              int64
PEA Ocupada                                                                                        int64
PEA Desocupada                                                                                     int64
Población no económicamente activa (PNEA)                                                          int64
PNEA Disponible                                                                                    int64
PNEA No disponible                                                                                 int64
3. Población ocupada por                                                                           int64
3.1 Posición en la ocupación                                                                       int64
Trabajadores subordinados y remunerados                                                            int64
Empleadores                                                                                        int64
Trabajadores por cuenta propia                                                                     int64
Trabajadores no remunerados                                                                        int64
No especificado                                                                                    int64
3.2 Sector de actividad económica                                                                  int64
Primario                                                                                           int64
Agricultura, ganadería, silvicultura, caza y pesca                                                 int64
Secundario                                                                                         int64
Industria extractiva, de la electricidad y manufacturera                                           int64
Construcción                                                                                       int64
Terciario                                                                                          int64
Comercio                                                                                           int64
Restaurantes y servicios de alojamiento, transportes, comunicaciones, correo y almacenamiento      int64
Servicios profesionales, financieros y corporativos                                                int64
Servicios sociales, gobierno y organismos internacionales                                          int64
Servicios diversos                                                                                 int64
No especificado.1                                                                                  int64
3.3 Nivel de ingresos                                                                              int64
Hasta un salario mínimo                                                                            int64
Más de 1 hasta 2 salarios mínimos                                                                  int64
Más de 2 hasta 3 salarios mínimos                                                                  int64
Más de 3 hasta 5 salarios mínimos                                                                  int64
Más de 5 salarios mínimos                                                                          int64
No recibe ingresos                                                                                 int64
No especificado.2                                                                                  int64
3.6 Ámbito y tamaño de la unidad económica                                                         int64
Ámbito agropecuario                                                                                int64
Ámbito no agropecuario                                                                             int64
Micronegocios                                                                                      int64
Pequeños establecimientos                                                                          int64
Medianos establecimientos                                                                          int64
Grandes establecimientos                                                                           int64
Gobierno y otros                                                                                   int64
No especificado.3                                                                                  int64
3.7 Distribución por tipo de unidad económica                                                      int64
Empresas y negocios                                                                                int64
Instituciones                                                                                      int64
Sector de los hogares                                                                              int64
Situaciones de carácter especial y no especificadas                                                int64
3.8 Condición de informalidad                                                                    float64
Ocupación formal                                                                                 float64
Ocupación informal                                                                               float64
Sector informal                                                                                  float64
Fuera de sector informal                                                                         float64
Tasa de desocupación de la población económicamente activa                                       float64
COVID.19                                                                                           int64
dtype: object

In [47]:
#Obtenemos los datos de manera limpia borrando todos nuestros nans pero esto solo nos trae conflicto por ello sera mejor usar datos

datos_sin_nan= pd.read_csv("https://raw.githubusercontent.com/McGilfordJose/BEDU/main/Python/Datasets/Consolidado.csv", encoding='ISO-8859-1')
datos_sin_nan = datos_sin_nan.dropna()
datos_sin_nan

      Año  ... COVID.19
158  2018  ...        0
159  2018  ...        0
160  2018  ...        0
161  2018  ...        0
162  2018  ...        0
163  2018  ...        0
164  2018  ...        0
165  2018  ...        0
166  2018  ...        0
167  2018  ...        0
168  2019  ...        0
169  2019  ...        0
170  2019  ...        0
171  2019  ...        0
172  2019  ...        0
173  2019  ...        0
174  2019  ...        0
175  2019  ...        0
176  2019  ...        0
177  2019  ...        0
178  2019  ...        0
179  2019  ...        0
180  2020  ...        0
181  2020  ...        0
182  2020  ...        0
186  2020  ...        1
187  2020  ...        1
188  2020  ...        1
189  2020  ...        1
190  2020  ...        1
191  2020  ...        1

[31 rows x 59 columns]